AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'api-collection/**/*'
  SuggestExtensions: false
  TargetRubyVersion: 3.1.3
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Lint/AmbiguousBlockAssociation:
  Exclude: ["spec/**/*"] # Rspec syntax is sweetest with a side of "ambiguous block association"
Metrics/AbcSize:
  Max: 18
Metrics/BlockLength:
  AllowedMethods: ["describe", "context", "rails_admin", "factory", "define", "namespace", "create_table", "included", "class_methods"]
Metrics/ClassLength:
  Max: 120
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 14
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
Naming/VariableNumber:
  Enabled: false
# Style/BracesAroundHashParameters:
#   EnforcedStyle: context_dependent
Style/ClassAndModuleChildren:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
# Style/StringLiterals:
  # EnforcedStyle: single_quotes
Style/SymbolArray:
  MinSize: 4